- README.md
- package-lock.json
- package.json
- src/version.js
Now that the file is on npm, we can direct people the unpkg cdn for the frontend-only use case.
None,
> added cdn link to readme for ease of use

- README.md
- demo/frames.html
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
The text on the "Submit" button is now able to be customized with the ULabel constructor as follows
```javascript
let ulabel = new ULabel(
"container", 
["/images/cs-demo-0.png", "/images/cs-demo-1.png", "/images/cs-demo-2.png"], 
"DemoUser",
{
"name": "<custom text here>",
"hook": on_submit
},
subtasks
);
```
Additionally, subtasks may now be specified as read-only by including a `read_only: true` attribute in the subtask configuration, but an annotation must have at least one subtask that is not read-only, otherwise a fatal error is thrown during construction.
See description.
> V4 updates

- api_spec.md
- changelog.md
- dist/ulabel.js
- package-lock.json
- src/index.js
Added `.to(fn, callback)` to the ULabel object, which will apply a callback to any valid ULabel function.
Useful for implementing custom behavior as well as debugging.
None
> Generic Callbacks

- changelog.md
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
There was an issue resuming from sessions with nonspatial annotations. `this.state` was being referenced before set. This has been fixed. 
None.
> Nonspatial Annotations in resume_from

- api_spec.md
- changelog.md
- demo/getset.html
- dist/ulabel.js
- package-lock.json
- src/blobs.js
- src/index.js
See `demo/getset.html` for an example.
*(string) => array* -- Gets the current list of annotations within the provided subtask.
*(array, string) => void* -- Sets the annotations for the provided subtask.
None, but note that undo/redo stacks are reset after `set_annotations` is called.
> Added Getter and Setter

- api_spec.md
- changelog.md
- demo/frames.html
- dist/ulabel.js
- package-lock.json
- package.json
- pull_request_template.md
- src/blobs.js
- src/index.js
- src/version.js
The constructor now accepts a link to a document with instructions, and the submit callback now binds the ulabel instance so that `set_saved()` can be called before page unloading, if desired. Finally, the new annotation mode of "Points" has been added.
None.
> Instructions

- index.d.ts
- package.json
- src/index.js
I am using this labeler in my current project.
I had to make some changes so I am able to properly import it in my angular application.
- Added basic `typescript` typings
- Fixed the main property in `package.json` so it points to a valid file. I also added the `module` field which points to the es6 module at the `src` folder
- I moved `express` to the `dev-dependencies` because users of this module do not need to install express for the frontend only component.
- I exported the `ULabel` class in the module so I can import it directly without accessing it via `window.ULabel`
None
> Fixed minor problems

- changelog.md
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
- Allow submission when page first loads without having to make an edit first
None.
> empty submit support

- api_spec.md
- changelog.md
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
- Fixed issue with detecting undo/redo on Firefox and Mac
- Detected shift+scroll for zooming as well as cmd/ctrl+scroll
- Fixed small issue with beforeunload warning
None.
> fixed issue with keyboard shortcuts on ff and mac

- changelog.md
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
- ULabel now allows for classification payloads without items for certain classes, and just assumes that omitted classes have a confidence of zero
None.
> added feature along with associated error checking

- .gitignore
- changelog.md
- dist/ulabel.js
- package-lock.json
- package.json
- src/index.js
- src/version.js
Calling set annotations assumed a `spatial_payload` exists when that's not the case for frame or global annotations.
Added a check for this.
None
> Fix Frame Set Annotations

- dist/ulabel.js
- index.d.ts
- package-lock.json
- package.json
- src/blobs.js
- src/index.js
- src/toolbox.js
- src/toolbox.ts
Added the Recolor Annotations toolbox item which will change the color of the actively selected type of annotation. Additionally added a vanish mode to the Change Annotation Resize toolbox item. Removed the medium button from the Change Annotation Resize toolbox item because it wasn't being used. Additionally added key-binds for changing the line size.
none
> Annotation color

- dist/ulabel.js
- src/drawing_utilities.js
- src/drawing_utilities.ts
Around 1% of annotations would flicker between fully colored in and completely white while the gradient max slider was being changed. This should now be fixed.
none
> Fixed incorrect logic in how the gradient was applied

- dist/ulabel.js
- src/drawing_utilities.js
- src/index.js
While moving functions over to the new annotation_operators.ts file I forgot to delete the old version of the function from index.js. It is now removed.
none
> removed unused method

- dist/ulabel.js
- src/toolbox.js
- src/toolbox.ts
If an annotation had a parent id that wasn't one of the annotations in the current subtask then check_for_human_deprecated would break. Should be fixed
none
> another deprecation fix

- dist/ulabel.js
- src/geometric_utils.js
- src/geometric_utils.ts
get_line_equation_through_points returns null when its given the same two points. When that happens get_nearest_point_on_segment would then receive a null object and we'd get an error. This just checks to make sure that the line object we receive isn't null
none
> make sure eq isn't null in get_nearest_point_on_segment

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/index.js
- src/toolbox.js
- src/toolbox.ts
Consolidated ulabel's built-in default config and the configuration class. Now when ulabel is constructed it will add an instance of the config to itself. All of the ulabel config stuff is then added to the configuration class. You can now also pass in new config data to ulabel's construction and it will be added to the configuration class. Also removed the configuration's dependency on ulabel as it was only used for constructing the toolbox, and it really didn't need to be there.
none
> New configuration

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/toolbox.js
- src/toolbox.ts
- tsconfig.json
Can pass in keypoint slider default to config, as well as a boolean to control if it filters on load or not
none
> Config updates

- dist/ulabel.js
- src/toolbox.js
- src/toolbox.ts
deprecate_annotations now updates both the keypoint slider value to whatever value was passed into it, as well as the keypoint slider label. This allows us to call the deprecate_annotations method from anywhere and the slider will be updated accordingly.
none
> Can now use keypoint slider functionality without moving keypoint slider

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/toolbox.js
- src/toolbox.ts
Added that ability to change the default annotation size in the config. Additionally saves a cookie with the size of the annotations per subtask. On load, uses the cookie size for the annotations if it exists. If cookie doesn't exist, then uses the config's default. If neither exist, then if uses the size saved to the annotation like before this pull request.
none
> On load check for annotation size cookie or config default

- demo/multi-class.html
- dist/ulabel.js
- src/index.js
Previous workflow was:
- Find annotations where cursor is within bounding box
- Find closest keypoints (ends of polygons/polylines etc) within a range defined by the edit handle
- If no endpoints, search along segments within a range defined by the edit handle
Change was to remove the range on the last point, so if not within range of a keypoint, search along all segments.
The issue was that the second two steps wouldn't produce anything as the range was too small to be relevant, so removing it for the second case solves some hovering irregularities.
Might need a future rework.
Broke things being broken
> better edit candidates

- dist/ulabel.js
- src/toolbox.js
- src/toolbox.ts
Page wouldn't load if the keypoint slider tried to run deprecate_annotations on load. This is because it was passing an incorrect parameter to deprecate_annotations. This is now fixed
none
> Fixed KeypointSliderItem passing in incorrect parameter

- dist/ulabel.js
- src/blobs.js
We decided to change the toolbox to be centered. This does that.
none
> Change css styling

- dist/ulabel.js
- index.d.ts
- src/toolbox.js
- src/toolbox.ts
Proposed in #75 
Pressing the "V" key will vanish all subtasks. Technically it swaps the vanished state of all subtasks, so if one subtask is vanished and one is not then they will switch, which seems like preferred behavior to me. 
none
> Vanish all

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/index.js
Proposed in #76 
Added a keybind to delete the "active" annotation. Currently the keybind is set to "d", but it can be changed in the config.
None
> Delete on hover

- dist/ulabel.js
- src/index.js
Currently certain dialogs show up when you hover over an annotation. This adds an additional dialog that shows the annotation's confidence.
none
> Add confidence dialog

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/index.js
Proposed in #45 
Adds a keybind to switch between active subtasks. Currently the keybind is z but is able to be changed in the config.
none
> Add keybind to switch between subtasks

- dist/ulabel.js
- index.d.ts
- src/configuration.js
- src/configuration.ts
- src/index.js
- src/toolbox.js
- src/toolbox.ts
Adds a keybind to toggle the current annotation mode. Keybind is currently "u", but is configurable in the configuration.
none
> Added keybind for toggling annotation mode

- dist/ulabel.js
- src/configuration.js
- src/configuration.ts
- src/index.js
- src/toolbox.js
- src/toolbox.ts
This changes the submit button by turning it into a toolbox item. Currently the submit button is created by after we create the toolbox, then we create the submit button and append its html to the toolbox. I was asked to add support for multiple submit buttons, so it made sense to update it and make it a toolbox item while I was at it. 
Removed the "submit-button" id from the submit button and now all submit buttons have a "submit-button" class. This may break something in our py-mfstand frontend.
> Add support for an arbitrary quantity of submit buttons

- dist/ulabel.js
- src/configuration.ts
- src/index.js
Add ability to pass in toolbox order to ulabel constructor. The create toolbox was created to allow a custom toolbox order to be passed in, we just never allowed you to pass one into the ulabel constructor
none
> Add support for toolbox order to be passed into ulabel constructor

- .github/workflows/create_github_release.yml
Replace `tag-it` workflow with one that creates both a tag and a github release.
no
> Create github release

- README.md
Adds a section to the README linking to [ulabel-react-demo](https://github.com/joshua-dean/ulabel-react-demo/),
a project demonstrating integration of ULabel into a React project.
Closes #42 and closes #51. Open new issues if you have a specific use case not covered by the demo.
no API changes
> Add README section on react integration
